Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> for i in range(1, 2001):
	if % 2 == 0:
		
SyntaxError: invalid syntax
>>> for i in range(1,2001):
	if i % 2 ==0:
		print'Number is ' + str(i) + '. This is an odd number.'
	else:
		print'Number is ' + str(i) + '. This is n even number.'

		
Number is 1. This is n even number.
Number is 2. This is an odd number.
Number is 3. This is n even number.
Number is 4. This is an odd number.
Number is 5. This is n even number.
Number is 6. This is an odd number.
Number is 7. This is n even number.
Number is 8. This is an odd number.
Number is 9. This is n even number.
Number is 10. This is an odd number.
Number is 11. This is n even number.
Number is 12. This is an odd number.
Number is 13. This is n even number.
Number is 14. This is an odd number.
Number is 15. This is n even number.
Number is 16. This is an odd number.
Number is 17. This is n even number.
Number is 18. This is an odd number.
Number is 19. This is n even number.
Number is 20. This is an odd number.
Number is 21. This is n even number.
Number is 22. This is an odd number.
Number is 23. This is n even number.
Number is 24. This is an odd number.
Number is 25. This is n even number.
Number is 26. This is an odd number.
Number is 27. This is n even number.
Number is 28. This is an odd number.
Number is 29. This is n even number.
Number is 30. This is an odd number.
Number is 31. This is n even number.
Number is 32. This is an odd number.
Number is 33. This is n even number.
Number is 34. This is an odd number.
Number is 35. This is n even number.
Number is 36. This is an odd number.
Number is 37. This is n even number.
Number is 38. This is an odd number.
Number is 39. This is n even number.
Number is 40. This is an odd number.
Number is 41. This is n even number.
Number is 42. This is an odd number.
Number is 43. This is n even number.
Number is 44. This is an odd number.
Number is 45. This is n even number.
Number is 46. This is an odd number.
Number is 47. This is n even number.
Number is 48. This is an odd number.
Number is 49. This is n even number.
Number is 50. This is an odd number.
Number is 51. This is n even number.
Number is 52. This is an odd number.
Number is 53. This is n even number.
Number is 54. This is an odd number.
Number is 55. This is n even number.
Number is 56. This is an odd number.
Number is 57. This is n even number.
Number is 58. This is an odd number.
Number is 59. This is n even number.
Number is 60. This is an odd number.
Number is 61. This is n even number.
Number is 62. This is an odd number.
Number is 63. This is n even number.
Number is 64. This is an odd number.
Number is 65. This is n even number.
Number is 66. This is an odd number.
Number is 67. This is n even number.
Number is 68. This is an odd number.
Number is 69. This is n even number.
Number is 70. This is an odd number.
Number is 71. This is n even number.
Number is 72. This is an odd number.
Number is 73. This is n even number.
Number is 74. This is an odd number.
Number is 75. This is n even number.
Number is 76. This is an odd number.
Number is 77. This is n even number.
Number is 78. This is an odd number.
Number is 79. This is n even number.
Number is 80. This is an odd number.
Number is 81. This is n even number.
Number is 82. This is an odd number.
Number is 83. This is n even number.
Number is 84. This is an odd number.
Number is 85. This is n even number.
Number is 86. This is an odd number.
Number is 87. This is n even number.
Number is 88. This is an odd number.
Number is 89. This is n even number.
Number is 90. This is an odd number.
Number is 91. This is n even number.
Number is 92. This is an odd number.
Number is 93. This is n even number.
Number is 94. This is an odd number.
Number is 95. This is n even number.
Number is 96. This is an odd number.
Number is 97. This is n even number.
Number is 98. This is an odd number.
Number is 99. This is n even number.
Number is 100. This is an odd number.
Number is 101. This is n even number.
Number is 102. This is an odd number.
Number is 103. This is n even number.
Number is 104. This is an odd number.
Number is 105. This is n even number.
Number is 106. This is an odd number.
Number is 107. This is n even number.
Number is 108. This is an odd number.
Number is 109. This is n even number.
Number is 110. This is an odd number.
Number is 111. This is n even number.
Number is 112. This is an odd number.
Number is 113. This is n even number.
Number is 114. This is an odd number.
Number is 115. This is n even number.
Number is 116. This is an odd number.
Number is 117. This is n even number.
Number is 118. This is an odd number.
Number is 119. This is n even number.
Number is 120. This is an odd number.
Number is 121. This is n even number.
Number is 122. This is an odd number.
Number is 123. This is n even number.
Number is 124. This is an odd number.
Number is 125. This is n even number.
Number is 126. This is an odd number.
Number is 127. This is n even number.
Number is 128. This is an odd number.
Number is 129. This is n even number.
Number is 130. This is an odd number.
Number is 131. This is n even number.
Number is 132. This is an odd number.
Number is 133. This is n even number.
Number is 134. This is an odd number.
Number is 135. This is n even number.
Number is 136. This is an odd number.
Number is 137. This is n even number.
Number is 138. This is an odd number.
Number is 139. This is n even number.
Number is 140. This is an odd number.
Number is 141. This is n even number.
Number is 142. This is an odd number.
Number is 143. This is n even number.
Number is 144. This is an odd number.
Number is 145. This is n even number.
Number is 146. This is an odd number.
Number is 147. This is n even number.
Number is 148. This is an odd number.
Number is 149. This is n even number.
Number is 150. This is an odd number.
Number is 151. This is n even number.
Number is 152. This is an odd number.
Number is 153. This is n even number.
Number is 154. This is an odd number.
Number is 155. This is n even number.
Number is 156. This is an odd number.
Number is 157. This is n even number.
Number is 158. This is an odd number.
Number is 159. This is n even number.
Number is 160. This is an odd number.
Number is 161. This is n even number.
Number is 162. This is an odd number.
Number is 163. This is n even number.
Number is 164. This is an odd number.
Number is 165. This is n even number.
Number is 166. This is an odd number.
Number is 167. This is n even number.
Number is 168. This is an odd number.
Number is 169. This is n even number.
Number is 170. This is an odd number.
Number is 171. This is n even number.
Number is 172. This is an odd number.
Number is 173. This is n even number.
Number is 174. This is an odd number.
Number is 175. This is n even number.
Number is 176. This is an odd number.
Number is 177. This is n even number.
Number is 178. This is an odd number.
Number is 179. This is n even number.
Number is 180. This is an odd number.
Number is 181. This is n even number.
Number is 182. This is an odd number.
Number is 183. This is n even number.
Number is 184. This is an odd number.
Number is 185. This is n even number.
Number is 186. This is an odd number.
Number is 187. This is n even number.
Number is 188. This is an odd number.
Number is 189. This is n even number.
Number is 190. This is an odd number.
Number is 191. This is n even number.
Number is 192. This is an odd number.
Number is 193. This is n even number.
Number is 194. This is an odd number.
Number is 195. This is n even number.
Number is 196. This is an odd number.
Number is 197. This is n even number.
Number is 198. This is an odd number.
Number is 199. This is n even number.
Number is 200. This is an odd number.
Number is 201. This is n even number.
Number is 202. This is an odd number.
Number is 203. This is n even number.
Number is 204. This is an odd number.
Number is 205. This is n even number.
Number is 206. This is an odd number.
Number is 207. This is n even number.
Number is 208. This is an odd number.
Number is 209. This is n even number.
Number is 210. This is an odd number.
Number is 211. This is n even number.
Number is 212. This is an odd number.
Number is 213. This is n even number.
Number is 214. This is an odd number.
Number is 215. This is n even number.
Number is 216. This is an odd number.
Number is 217. This is n even number.
Number is 218. This is an odd number.
Number is 219. This is n even number.
Number is 220. This is an odd number.
Number is 221. This is n even number.
Number is 222. This is an odd number.
Number is 223. This is n even number.
Number is 224. This is an odd number.
Number is 225. This is n even number.
Number is 226. This is an odd number.
Number is 227. This is n even number.
Number is 228. This is an odd number.
Number is 229. This is n even number.
Number is 230. This is an odd number.
Number is 231. This is n even number.
Number is 232. This is an odd number.
Number is 233. This is n even number.
Number is 234. This is an odd number.
Number is 235. This is n even number.
Number is 236. This is an odd number.
Number is 237. This is n even number.
Number is 238. This is an odd number.
Number is 239. This is n even number.
Number is 240. This is an odd number.
Number is 241. This is n even number.
Number is 242. This is an odd number.
Number is 243. This is n even number.
Number is 244. This is an odd number.
Number is 245. This is n even number.
Number is 246. This is an odd number.
Number is 247. This is n even number.
Number is 248. This is an odd number.
Number is 249. This is n even number.
Number is 250. This is an odd number.
Number is 251. This is n even number.
Number is 252. This is an odd number.
Number is 253. This is n even number.
Number is 254. This is an odd number.
Number is 255. This is n even number.
Number is 256. This is an odd number.
Number is 257. This is n even number.
Number is 258. This is an odd number.
Number is 259. This is n even number.
Number is 260. This is an odd number.
Number is 261. This is n even number.
Number is 262. This is an odd number.
Number is 263. This is n even number.
Number is 264. This is an odd number.
Number is 265. This is n even number.
Number is 266. This is an odd number.
Number is 267. This is n even number.
Number is 268. This is an odd number.
Number is 269. This is n even number.
Number is 270. This is an odd number.
Number is 271. This is n even number.
Number is 272. This is an odd number.
Number is 273. This is n even number.
Number is 274. This is an odd number.
Number is 275. This is n even number.
Number is 276. This is an odd number.
Number is 277. This is n even number.
Number is 278. This is an odd number.
Number is 279. This is n even number.
Number is 280. This is an odd number.
Number is 281. This is n even number.
Number is 282. This is an odd number.
Number is 283. This is n even number.
Number is 284. This is an odd number.
Number is 285. This is n even number.
Number is 286. This is an odd number.
Number is 287. This is n even number.
Number is 288. This is an odd number.
Number is 289. This is n even number.
Number is 290. This is an odd number.
Number is 291. This is n even number.
Number is 292. This is an odd number.
Number is 293. This is n even number.
Number is 294. This is an odd number.
Number is 295. This is n even number.
Number is 296. This is an odd number.
Number is 297. This is n even number.
Number is 298. This is an odd number.
Number is 299. This is n even number.
Number is 300. This is an odd number.
Number is 301. This is n even number.
Number is 302. This is an odd number.
Number is 303. This is n even number.
Number is 304. This is an odd number.
Number is 305. This is n even number.
Number is 306. This is an odd number.
Number is 307. This is n even number.
Number is 308. This is an odd number.
Number is 309. This is n even number.
Number is 310. This is an odd number.
Number is 311. This is n even number.
Number is 312. This is an odd number.
Number is 313. This is n even number.
Number is 314. This is an odd number.
Number is 315. This is n even number.
Number is 316. This is an odd number.
Number is 317. This is n even number.
Number is 318. This is an odd number.
Number is 319. This is n even number.
Number is 320. This is an odd number.
Number is 321. This is n even number.
Number is 322. This is an odd number.
Number is 323. This is n even number.
Number is 324. This is an odd number.
Number is 325. This is n even number.
Number is 326. This is an odd number.
Number is 327. This is n even number.
Number is 328. This is an odd number.
Number is 329. This is n even number.
Number is 330. This is an odd number.
Number is 331. This is n even number.
Number is 332. This is an odd number.
Number is 333. This is n even number.
Number is 334. This is an odd number.
Number is 335. This is n even number.
Number is 336. This is an odd number.
Number is 337. This is n even number.
Number is 338. This is an odd number.
Number is 339. This is n even number.
Number is 340. This is an odd number.
Number is 341. This is n even number.
Number is 342. This is an odd number.
Number is 343. This is n even number.
Number is 344. This is an odd number.
Number is 345. This is n even number.
Number is 346. This is an odd number.
Number is 347. This is n even number.
Number is 348. This is an odd number.
Number is 349. This is n even number.
Number is 350. This is an odd number.
Number is 351. This is n even number.
Number is 352. This is an odd number.
Number is 353. This is n even number.
Number is 354. This is an odd number.
Number is 355. This is n even number.
Number is 356. This is an odd number.
Number is 357. This is n even number.
Number is 358. This is an odd number.
Number is 359. This is n even number.
Number is 360. This is an odd number.
Number is 361. This is n even number.
Number is 362. This is an odd number.
Number is 363. This is n even number.
Number is 364. This is an odd number.
Number is 365. This is n even number.
Number is 366. This is an odd number.
Number is 367. This is n even number.
Number is 368. This is an odd number.
Number is 369. This is n even number.
Number is 370. This is an odd number.
Number is 371. This is n even number.
Number is 372. This is an odd number.
Number is 373. This is n even number.
Number is 374. This is an odd number.
Number is 375. This is n even number.
Number is 376. This is an odd number.
Number is 377. This is n even number.
Number is 378. This is an odd number.
Number is 379. This is n even number.
Number is 380. This is an odd number.
Number is 381. This is n even number.
Number is 382. This is an odd number.
Number is 383. This is n even number.
Number is 384. This is an odd number.
Number is 385. This is n even number.
Number is 386. This is an odd number.
Number is 387. This is n even number.
Number is 388. This is an odd number.
Number is 389. This is n even number.
Number is 390. This is an odd number.
Number is 391. This is n even number.
Number is 392. This is an odd number.
Number is 393. This is n even number.
Number is 394. This is an odd number.
Number is 395. This is n even number.
Number is 396. This is an odd number.
Number is 397. This is n even number.
Number is 398. This is an odd number.
Number is 399. This is n even number.
Number is 400. This is an odd number.
Number is 401. This is n even number.
Number is 402. This is an odd number.
Number is 403. This is n even number.
Number is 404. This is an odd number.
Number is 405. This is n even number.
Number is 406. This is an odd number.
Number is 407. This is n even number.
Number is 408. This is an odd number.
Number is 409. This is n even number.
Number is 410. This is an odd number.
Number is 411. This is n even number.
Number is 412. This is an odd number.
Number is 413. This is n even number.
Number is 414. This is an odd number.
Number is 415. This is n even number.
Number is 416. This is an odd number.
Number is 417. This is n even number.
Number is 418. This is an odd number.
Number is 419. This is n even number.
Number is 420. This is an odd number.
Number is 421. This is n even number.
Number is 422. This is an odd number.
Number is 423. This is n even number.
Number is 424. This is an odd number.
Number is 425. This is n even number.
Number is 426. This is an odd number.
Number is 427. This is n even number.
Number is 428. This is an odd number.
Number is 429. This is n even number.
Number is 430. This is an odd number.
Number is 431. This is n even number.
Number is 432. This is an odd number.
Number is 433. This is n even number.
Number is 434. This is an odd number.
Number is 435. This is n even number.
Number is 436. This is an odd number.
Number is 437. This is n even number.
Number is 438. This is an odd number.
Number is 439. This is n even number.
Number is 440. This is an odd number.
Number is 441. This is n even number.
Number is 442. This is an odd number.
Number is 443. This is n even number.
Number is 444. This is an odd number.
Number is 445. This is n even number.
Number is 446. This is an odd number.
Number is 447. This is n even number.
Number is 448. This is an odd number.
Number is 449. This is n even number.
Number is 450. This is an odd number.
Number is 451. This is n even number.
Number is 452. This is an odd number.
Number is 453. This is n even number.
Number is 454. This is an odd number.
Number is 455. This is n even number.
Number is 456. This is an odd number.
Number is 457. This is n even number.
Number is 458. This is an odd number.
Number is 459. This is n even number.
Number is 460. This is an odd number.
Number is 461. This is n even number.
Number is 462. This is an odd number.
Number is 463. This is n even number.
Number is 464. This is an odd number.
Number is 465. This is n even number.
Number is 466. This is an odd number.
Number is 467. This is n even number.
Number is 468. This is an odd number.
Number is 469. This is n even number.
Number is 470. This is an odd number.
Number is 471. This is n even number.
Number is 472. This is an odd number.
Number is 473. This is n even number.
Number is 474. This is an odd number.
Number is 475. This is n even number.
Number is 476. This is an odd number.
Number is 477. This is n even number.
Number is 478. This is an odd number.
Number is 479. This is n even number.
Number is 480. This is an odd number.
Number is 481. This is n even number.
Number is 482. This is an odd number.
Number is 483. This is n even number.
Number is 484. This is an odd number.
Number is 485. This is n even number.
Number is 486. This is an odd number.
Number is 487. This is n even number.
Number is 488. This is an odd number.
Number is 489. This is n even number.
Number is 490. This is an odd number.
Number is 491. This is n even number.
Number is 492. This is an odd number.
Number is 493. This is n even number.
Number is 494. This is an odd number.
Number is 495. This is n even number.
Number is 496. This is an odd number.
Number is 497. This is n even number.
Number is 498. This is an odd number.
Number is 499. This is n even number.
Number is 500. This is an odd number.
Number is 501. This is n even number.
Number is 502. This is an odd number.
Number is 503. This is n even number.
Number is 504. This is an odd number.
Number is 505. This is n even number.
Number is 506. This is an odd number.
Number is 507. This is n even number.
Number is 508. This is an odd number.
Number is 509. This is n even number.
Number is 510. This is an odd number.
Number is 511. This is n even number.
Number is 512. This is an odd number.
Number is 513. This is n even number.
Number is 514. This is an odd number.
Number is 515. This is n even number.
Number is 516. This is an odd number.
Number is 517. This is n even number.
Number is 518. This is an odd number.
Number is 519. This is n even number.
Number is 520. This is an odd number.
Number is 521. This is n even number.
Number is 522. This is an odd number.
Number is 523. This is n even number.
Number is 524. This is an odd number.
Number is 525. This is n even number.
Number is 526. This is an odd number.
Number is 527. This is n even number.
Number is 528. This is an odd number.
Number is 529. This is n even number.
Number is 530. This is an odd number.
Number is 531. This is n even number.
Number is 532. This is an odd number.
Number is 533. This is n even number.
Number is 534. This is an odd number.
Number is 535. This is n even number.
Number is 536. This is an odd number.
Number is 537. This is n even number.
Number is 538. This is an odd number.
Number is 539. This is n even number.
Number is 540. This is an odd number.
Number is 541. This is n even number.
Number is 542. This is an odd number.
Number is 543. This is n even number.
Number is 544. This is an odd number.
Number is 545. This is n even number.
Number is 546. This is an odd number.
Number is 547. This is n even number.
Number is 548. This is an odd number.
Number is 549. This is n even number.
Number is 550. This is an odd number.
Number is 551. This is n even number.
Number is 552. This is an odd number.
Number is 553. This is n even number.
Number is 554. This is an odd number.
Number is 555. This is n even number.
Number is 556. This is an odd number.
Number is 557. This is n even number.
Number is 558. This is an odd number.
Number is 559. This is n even number.
Number is 560. This is an odd number.
Number is 561. This is n even number.
Number is 562. This is an odd number.
Number is 563. This is n even number.
Number is 564. This is an odd number.
Number is 565. This is n even number.
Number is 566. This is an odd number.
Number is 567. This is n even number.
Number is 568. This is an odd number.
Number is 569. This is n even number.
Number is 570. This is an odd number.
Number is 571. This is n even number.
Number is 572. This is an odd number.
Number is 573. This is n even number.
Number is 574. This is an odd number.
Number is 575. This is n even number.
Number is 576. This is an odd number.
Number is 577. This is n even number.
Number is 578. This is an odd number.
Number is 579. This is n even number.
Number is 580. This is an odd number.
Number is 581. This is n even number.
Number is 582. This is an odd number.
Number is 583. This is n even number.
Number is 584. This is an odd number.
Number is 585. This is n even number.
Number is 586. This is an odd number.
Number is 587. This is n even number.
Number is 588. This is an odd number.
Number is 589. This is n even number.
Number is 590. This is an odd number.
Number is 591. This is n even number.
Number is 592. This is an odd number.
Number is 593. This is n even number.
Number is 594. This is an odd number.
Number is 595. This is n even number.
Number is 596. This is an odd number.
Number is 597. This is n even number.
Number is 598. This is an odd number.
Number is 599. This is n even number.
Number is 600. This is an odd number.
Number is 601. This is n even number.
Number is 602. This is an odd number.
Number is 603. This is n even number.
Number is 604. This is an odd number.
Number is 605. This is n even number.
Number is 606. This is an odd number.
Number is 607. This is n even number.
Number is 608. This is an odd number.
Number is 609. This is n even number.
Number is 610. This is an odd number.
Number is 611. This is n even number.
Number is 612. This is an odd number.
Number is 613. This is n even number.
Number is 614. This is an odd number.
Number is 615. This is n even number.
Number is 616. This is an odd number.
Number is 617. This is n even number.
Number is 618. This is an odd number.
Number is 619. This is n even number.
Number is 620. This is an odd number.
Number is 621. This is n even number.
Number is 622. This is an odd number.
Number is 623. This is n even number.
Number is 624. This is an odd number.
Number is 625. This is n even number.
Number is 626. This is an odd number.
Number is 627. This is n even number.
Number is 628. This is an odd number.
Number is 629. This is n even number.
Number is 630. This is an odd number.
Number is 631. This is n even number.
Number is 632. This is an odd number.
Number is 633. This is n even number.
Number is 634. This is an odd number.
Number is 635. This is n even number.
Number is 636. This is an odd number.
Number is 637. This is n even number.
Number is 638. This is an odd number.
Number is 639. This is n even number.
Number is 640. This is an odd number.
Number is 641. This is n even number.
Number is 642. This is an odd number.
Number is 643. This is n even number.
Number is 644. This is an odd number.
Number is 645. This is n even number.
Number is 646. This is an odd number.
Number is 647. This is n even number.
Number is 648. This is an odd number.
Number is 649. This is n even number.
Number is 650. This is an odd number.
Number is 651. This is n even number.
Number is 652. This is an odd number.
Number is 653. This is n even number.
Number is 654. This is an odd number.
Number is 655. This is n even number.
Number is 656. This is an odd number.
Number is 657. This is n even number.
Number is 658. This is an odd number.
Number is 659. This is n even number.
Number is 660. This is an odd number.
Number is 661. This is n even number.
Number is 662. This is an odd number.
Number is 663. This is n even number.
Number is 664. This is an odd number.
Number is 665. This is n even number.
Number is 666. This is an odd number.
Number is 667. This is n even number.
Number is 668. This is an odd number.
Number is 669. This is n even number.
Number is 670. This is an odd number.
Number is 671. This is n even number.
Number is 672. This is an odd number.
Number is 673. This is n even number.
Number is 674. This is an odd number.
Number is 675. This is n even number.
Number is 676. This is an odd number.
Number is 677. This is n even number.
Number is 678. This is an odd number.
Number is 679. This is n even number.
Number is 680. This is an odd number.
Number is 681. This is n even number.
Number is 682. This is an odd number.
Number is 683. This is n even number.
Number is 684. This is an odd number.
Number is 685. This is n even number.
Number is 686. This is an odd number.
Number is 687. This is n even number.
Number is 688. This is an odd number.
Number is 689. This is n even number.
Number is 690. This is an odd number.
Number is 691. This is n even number.
Number is 692. This is an odd number.
Number is 693. This is n even number.
Number is 694. This is an odd number.
Number is 695. This is n even number.
Number is 696. This is an odd number.
Number is 697. This is n even number.
Number is 698. This is an odd number.
Number is 699. This is n even number.
Number is 700. This is an odd number.
Number is 701. This is n even number.
Number is 702. This is an odd number.
Number is 703. This is n even number.
Number is 704. This is an odd number.
Number is 705. This is n even number.
Number is 706. This is an odd number.
Number is 707. This is n even number.
Number is 708. This is an odd number.
Number is 709. This is n even number.
Number is 710. This is an odd number.
Number is 711. This is n even number.
Number is 712. This is an odd number.
Number is 713. This is n even number.
Number is 714. This is an odd number.
Number is 715. This is n even number.
Number is 716. This is an odd number.
Number is 717. This is n even number.
Number is 718. This is an odd number.
Number is 719. This is n even number.
Number is 720. This is an odd number.
Number is 721. This is n even number.
Number is 722. This is an odd number.
Number is 723. This is n even number.
Number is 724. This is an odd number.
Number is 725. This is n even number.
Number is 726. This is an odd number.
Number is 727. This is n even number.
Number is 728. This is an odd number.
Number is 729. This is n even number.
Number is 730. This is an odd number.
Number is 731. This is n even number.
Number is 732. This is an odd number.
Number is 733. This is n even number.
Number is 734. This is an odd number.
Number is 735. This is n even number.
Number is 736. This is an odd number.
Number is 737. This is n even number.
Number is 738. This is an odd number.
Number is 739. This is n even number.
Number is 740. This is an odd number.
Number is 741. This is n even number.
Number is 742. This is an odd number.
Number is 743. This is n even number.
Number is 744. This is an odd number.
Number is 745. This is n even number.
Number is 746. This is an odd number.
Number is 747. This is n even number.
Number is 748. This is an odd number.
Number is 749. This is n even number.
Number is 750. This is an odd number.
Number is 751. This is n even number.
Number is 752. This is an odd number.
Number is 753. This is n even number.
Number is 754. This is an odd number.
Number is 755. This is n even number.
Number is 756. This is an odd number.
Number is 757. This is n even number.
Number is 758. This is an odd number.
Number is 759. This is n even number.
Number is 760. This is an odd number.
Number is 761. This is n even number.
Number is 762. This is an odd number.
Number is 763. This is n even number.
Number is 764. This is an odd number.
Number is 765. This is n even number.
Number is 766. This is an odd number.
Number is 767. This is n even number.
Number is 768. This is an odd number.
Number is 769. This is n even number.
Number is 770. This is an odd number.
Number is 771. This is n even number.
Number is 772. This is an odd number.
Number is 773. This is n even number.
Number is 774. This is an odd number.
Number is 775. This is n even number.
Number is 776. This is an odd number.
Number is 777. This is n even number.
Number is 778. This is an odd number.
Number is 779. This is n even number.
Number is 780. This is an odd number.
Number is 781. This is n even number.
Number is 782. This is an odd number.
Number is 783. This is n even number.
Number is 784. This is an odd number.
Number is 785. This is n even number.
Number is 786. This is an odd number.
Number is 787. This is n even number.
Number is 788. This is an odd number.
Number is 789. This is n even number.
Number is 790. This is an odd number.
Number is 791. This is n even number.
Number is 792. This is an odd number.
Number is 793. This is n even number.
Number is 794. This is an odd number.
Number is 795. This is n even number.
Number is 796. This is an odd number.
Number is 797. This is n even number.
Number is 798. This is an odd number.
Number is 799. This is n even number.
Number is 800. This is an odd number.
Number is 801. This is n even number.
Number is 802. This is an odd number.
Number is 803. This is n even number.
Number is 804. This is an odd number.
Number is 805. This is n even number.
Number is 806. This is an odd number.
Number is 807. This is n even number.
Number is 808. This is an odd number.
Number is 809. This is n even number.
Number is 810. This is an odd number.
Number is 811. This is n even number.
Number is 812. This is an odd number.
Number is 813. This is n even number.
Number is 814. This is an odd number.
Number is 815. This is n even number.
Number is 816. This is an odd number.
Number is 817. This is n even number.
Number is 818. This is an odd number.
Number is 819. This is n even number.
Number is 820. This is an odd number.
Number is 821. This is n even number.
Number is 822. This is an odd number.
Number is 823. This is n even number.
Number is 824. This is an odd number.
Number is 825. This is n even number.
Number is 826. This is an odd number.
Number is 827. This is n even number.
Number is 828. This is an odd number.
Number is 829. This is n even number.
Number is 830. This is an odd number.
Number is 831. This is n even number.
Number is 832. This is an odd number.
Number is 833. This is n even number.
Number is 834. This is an odd number.
Number is 835. This is n even number.
Number is 836. This is an odd number.
Number is 837. This is n even number.
Number is 838. This is an odd number.
Number is 839. This is n even number.
Number is 840. This is an odd number.
Number is 841. This is n even number.
Number is 842. This is an odd number.
Number is 843. This is n even number.
Number is 844. This is an odd number.
Number is 845. This is n even number.
Number is 846. This is an odd number.
Number is 847. This is n even number.
Number is 848. This is an odd number.
Number is 849. This is n even number.
Number is 850. This is an odd number.
Number is 851. This is n even number.
Number is 852. This is an odd number.
Number is 853. This is n even number.
Number is 854. This is an odd number.
Number is 855. This is n even number.
Number is 856. This is an odd number.
Number is 857. This is n even number.
Number is 858. This is an odd number.
Number is 859. This is n even number.
Number is 860. This is an odd number.
Number is 861. This is n even number.
Number is 862. This is an odd number.
Number is 863. This is n even number.
Number is 864. This is an odd number.
Number is 865. This is n even number.
Number is 866. This is an odd number.
Number is 867. This is n even number.
Number is 868. This is an odd number.
Number is 869. This is n even number.
Number is 870. This is an odd number.
Number is 871. This is n even number.
Number is 872. This is an odd number.
Number is 873. This is n even number.
Number is 874. This is an odd number.
Number is 875. This is n even number.
Number is 876. This is an odd number.
Number is 877. This is n even number.
Number is 878. This is an odd number.
Number is 879. This is n even number.
Number is 880. This is an odd number.
Number is 881. This is n even number.
Number is 882. This is an odd number.
Number is 883. This is n even number.
Number is 884. This is an odd number.
Number is 885. This is n even number.
Number is 886. This is an odd number.
Number is 887. This is n even number.
Number is 888. This is an odd number.
Number is 889. This is n even number.
Number is 890. This is an odd number.
Number is 891. This is n even number.
Number is 892. This is an odd number.
Number is 893. This is n even number.
Number is 894. This is an odd number.
Number is 895. This is n even number.
